import hydra
import torch
from omegaconf import DictConfig
from tqdm import tqdm

from samplers import SAMPLERS
from experiments.sudoku.sudoku_utils import (
    build_unit_indices,
    clamp_clues,
    count_violations_batch,
)
from experiments.utils import fix_seed
from local_paths import REPO_DIR


def parse_puzzle(puzzle: str) -> torch.Tensor:
    cleaned = []
    for ch in puzzle:
        if ch.isdigit() or ch == ".":
            cleaned.append("0" if ch == "." else ch)
    flat = "".join(cleaned)
    if len(flat) != 81:
        raise ValueError(
            "Puzzle must have 81 digits (use 0 or . for blanks). "
            f"Got {len(flat)} characters."
        )
    digits = torch.tensor([int(ch) for ch in flat], dtype=torch.long)
    if (digits < 0).any() or (digits > 9).any():
        raise ValueError("Puzzle digits must be in [0, 9].")
    return digits.view(9, 9)


def render_grid(grid: torch.Tensor) -> str:
    lines = []
    for r in range(9):
        if r in (3, 6):
            lines.append("------+-------+------")
        row = []
        for c in range(9):
            if c in (3, 6):
                row.append("|")
            val = int(grid[r, c])
            row.append(str(val) if val > 0 else ".")
        lines.append(" ".join(row))
    return "\n".join(lines)


def soft_penalty(
    samples: torch.Tensor, row_idx: torch.Tensor, col_idx: torch.Tensor
) -> torch.Tensor:
    # samples: [B, 81, 9] one-hot
    batch_size, n_tokens = samples.shape[0], samples.shape[-1]
    sudoku_grid = samples.view(batch_size, 9, 9, n_tokens)
    units_sum = sudoku_grid[:, row_idx, col_idx, :].sum(dim=-2)
    return (units_sum - 1.0).square().sum()


def solve_one(
    clues: torch.Tensor,
    sampler: str,
    n_opt_steps: int,
    lr: float,
) -> torch.Tensor:
    row_idx, col_idx = build_unit_indices()
    row_idx = row_idx
    col_idx = col_idx

    logits = torch.zeros((1, 81, 9), requires_grad=True)
    optimizer = torch.optim.Adam([logits], lr=lr)

    sampler_fn = SAMPLERS[sampler.sampler_name] # this is one of redge, redge_cov, reindge, gumbel, st, reinmax
    pbar = tqdm(range(n_opt_steps), desc="Sudoku", unit="it")
    for _ in pbar:
        # Keep the given clues fixed by clamping their logits.
        with torch.no_grad():
            clamp_clues(logits, clue_vals=clues.view(1, -1))

        optimizer.zero_grad()

        # === Sampler usage ===
        # The sampler maps logits -> (approx) one-hot samples while keeping gradients.
        # Swapping this function changes *how* gradients flow through discrete samples.
        # We can treat the generated samples as if they were generated by a differentiable operation and use them for any downstream loss, as long as the rest of the computation is differentiable.
        samples = sampler_fn(logits=logits, **sampler)
        # =====================

        loss = soft_penalty(samples, row_idx, col_idx)
        loss.backward()
        optimizer.step()
        pbar.set_postfix(loss=f"{loss.item():.4f}")

    return samples.detach()


@hydra.main(
    version_base=None,
    config_path=str(REPO_DIR / "configs"),
    config_name="config",
)
def main(cfg: DictConfig) -> None:
    torch.set_default_device(cfg.device)
    clues = parse_puzzle(cfg.demo.puzzle)
    fix_seed(cfg.seed)
    print("Input puzzle:\n")
    print(render_grid(clues))

    samples = solve_one(
        clues=clues,
        sampler=cfg.sampler,
        n_opt_steps=cfg.n_opt_steps,
        lr=cfg.lr,
    )

    # Convert one-hot-ish samples into digits 1..9
    solved_digits = samples.argmax(dim=-1).view(9, 9) + 1

    row_idx, col_idx = build_unit_indices()
    row_idx = row_idx
    col_idx = col_idx
    violations, _ = count_violations_batch(samples, row_idx, col_idx)

    print("\nSolved grid (argmax):\n")
    print(render_grid(solved_digits.cpu()))
    print(f"\nTotal constraint violations: {int(violations.item())}")


if __name__ == "__main__":
    main()
